{% set name = "google-cloud-orchestration-airflow" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-orchestration-airflow-{{ version }}.tar.gz
  sha256: fd1ef44254a4bc861450d9c64267cfba318e16d24ee2cc280a32e146f9f9c73f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-api-core-grpc >=1.32.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.20.2,<5.0.0dev

test:
  imports:
    - google
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-orchestration-airflow
  summary: Cloud Composer API client library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
